apiVersion: consul.hashicorp.com/v1alpha1
kind: ExportedServices
metadata:
  name: default
spec:
  services:
    - name: mesh-gateway
      consumers:
        - partition: aks
    - name: product-api-db
      namespace: default
      consumers:
        - partition: aks
