apiVersion: consul.hashicorp.com/v1alpha1
kind: ExportedServices
metadata:
  name: aks
spec:
  services:
    - name: mesh-gateway
      consumers:
        - partition: default
    - name: product-api
      namespace: default
      consumers:
        - partition: default
