apiVersion: consul.hashicorp.com/v1alpha1
kind: ServiceIntentions
metadata:
  name: public-api
spec:
  sources:
    - name: frontend
      action: allow
    - name: nginx
      action: allow
  destination:
    name: public-api
---
apiVersion: consul.hashicorp.com/v1alpha1
kind: ServiceIntentions
metadata:
  name: products-api
spec:
  sources:
    - name: public-api
      action: allow
  destination:
    name: products-api
---
apiVersion: consul.hashicorp.com/v1alpha1
kind: ServiceIntentions
metadata:
  name: payments
spec:
  sources:
    - name: public-api
      action: allow
  destination:
    name: payments
---
apiVersion: consul.hashicorp.com/v1alpha1
kind: ServiceIntentions
metadata:
  # The metadata name is the destination service name and
  # matches the spec.destination.name value.
  name: product-api-to-db
  namespace: default
spec:
  sources:
    - name: product-api
      action: allow
      partition: aks1
      namespace: default
  destination:
    name: product-api-db
    namespace: default
---
apiVersion: consul.hashicorp.com/v1alpha1
kind: ServiceIntentions
metadata:
  name: frontend
spec:
  sources:
    - name: nginx
      action: allow
  destination:
    name: frontend
---
apiVersion: consul.hashicorp.com/v1alpha1
kind: ServiceIntentions
metadata:
  name: nginx
spec:
  destination:
    name: nginx
  sources:
    - name: "*"
      action: allow
